# SPDX-FileCopyrightText: 2025 Nextcloud GmbH and Nextcloud contributors
# SPDX-License-Identifier: AGPL-3.0-or-later
version = 1
SPDX-PackageName = "frontend_insight"
SPDX-PackageSupplier = "Nextcloud <info@nextcloud.com>"
SPDX-PackageDownloadLocation = "https://github.com/callmemagnus/nextcloud-frontendinsight"

[[annotations]]
path = ["l10n/**.js", "l10n/**.json"]
precedence = "aggregate"
SPDX-FileCopyrightText = "2025 Magnus Anderssen <magnus@magooweb.com>"
SPDX-License-Identifier = "AGPL-3.0-only AND (AGPL-3.0-or-later OR AGPL-3.0-only)"

[[annotations]]
path = ["composer.json", "composer.lock", ".php-cs-fixer.dist.php", ".gitignore", "psalm.xml", "tests/psalm-baseline.xml", ".nextcloudignore", "krankerl.toml"]
precedence = "aggregate"
SPDX-FileCopyrightText = "2025 Nextcloud GmbH and Nextcloud contributors"
SPDX-License-Identifier = "AGPL-3.0-or-later"

[[annotations]]
path = ["README.md", "appinfo/info.xml", "Makefile"]
precedence = "aggregate"
SPDX-FileCopyrightText = "2025 Magnus Anderssen <magnus@magooweb.com>"
SPDX-License-Identifier = "AGPL-3.0-or-later"

